; Put in the PHP-FPM conf.d directory. Shared by pools in this FPM instance.
opcache.enable=1
opcache.memory_consumption=32
opcache.interned_strings_buffer=4
opcache.max_accelerated_files=4000
opcache.validate_timestamps=1
expose_php=Off
