// @generated by tsquid-codegen. Do not edit.
import { createURI } from "@tsquid/routes/uri";
import { createRouteContextRegistry, type RouteContextValue } from "@tsquid/routes/context";

export enum RouteName {
  Home = "Home",
  ItemIndex = "ItemIndex",
  ItemNew = "ItemNew",
  ItemDetail = "ItemDetail",
  ItemEdit = "ItemEdit",
  LocationIndex = "LocationIndex",
  LocationNew = "LocationNew",
  LocationDetail = "LocationDetail",
  LocationEdit = "LocationEdit",
  InventoryIndex = "InventoryIndex",
  InventoryNew = "InventoryNew",
  InventoryDetail = "InventoryDetail",
  InventoryEdit = "InventoryEdit",
  InventoryItemDetail = "InventoryItemDetail",
  InventoryItemEdit = "InventoryItemEdit",
  InventoryLocationDetail = "InventoryLocationDetail",
  InventoryLocationEdit = "InventoryLocationEdit",
  InventoryStock = "InventoryStock",
  InventoryStockLocation = "InventoryStockLocation",
  UserIndex = "UserIndex",
  UserNew = "UserNew",
  UserDetail = "UserDetail",
}

export type HomeInputType = {
};
export const HomeURI = createURI<HomeInputType>("/", {});


export type ItemIndexInputType = {
  term?: string;
};
export const ItemIndexURI = createURI<ItemIndexInputType>("/items", {"term":{"kind":"string","optional":true}});


export type ItemNewInputType = {
  barcode?: string;
  term?: string;
};
export const ItemNewURI = createURI<ItemNewInputType>("/items/new", {"barcode":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type ItemDetailInputType = {
  id: string;
  term?: string;
};
export const ItemDetailURI = createURI<ItemDetailInputType>("/items/:id", {"id":{"kind":"string","optional":false},"term":{"kind":"string","optional":true}});


export type ItemEditInputType = {
  id: string;
  term?: string;
};
export const ItemEditURI = createURI<ItemEditInputType>("/items/:id/edit", {"id":{"kind":"string","optional":false},"term":{"kind":"string","optional":true}});


export type LocationIndexInputType = {
  term?: string;
};
export const LocationIndexURI = createURI<LocationIndexInputType>("/locations", {"term":{"kind":"string","optional":true}});


export type LocationNewInputType = {
  term?: string;
};
export const LocationNewURI = createURI<LocationNewInputType>("/locations/new", {"term":{"kind":"string","optional":true}});


export type LocationDetailInputType = {
  id: string;
  term?: string;
};
export const LocationDetailURI = createURI<LocationDetailInputType>("/locations/:id", {"id":{"kind":"string","optional":false},"term":{"kind":"string","optional":true}});


export type LocationEditInputType = {
  id: string;
  term?: string;
};
export const LocationEditURI = createURI<LocationEditInputType>("/locations/:id/edit", {"id":{"kind":"string","optional":false},"term":{"kind":"string","optional":true}});


export type InventoryIndexInputType = {
  location?: string;
  term?: string;
};
export const InventoryIndexURI = createURI<InventoryIndexInputType>("/inventory", {"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryNewInputType = {
  location?: string;
  term?: string;
};
export const InventoryNewURI = createURI<InventoryNewInputType>("/inventory/new", {"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryDetailInputType = {
  id: string;
  location?: string;
  term?: string;
};
export const InventoryDetailURI = createURI<InventoryDetailInputType>("/inventory/:id", {"id":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryEditInputType = {
  id: string;
  location?: string;
  term?: string;
};
export const InventoryEditURI = createURI<InventoryEditInputType>("/inventory/:id/edit", {"id":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryItemDetailInputType = {
  id: string;
  location?: string;
  term?: string;
};
export const InventoryItemDetailURI = createURI<InventoryItemDetailInputType>("/inventory/items/:id", {"id":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryItemEditInputType = {
  id: string;
  location?: string;
  term?: string;
};
export const InventoryItemEditURI = createURI<InventoryItemEditInputType>("/inventory/items/:id/edit", {"id":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryLocationDetailInputType = {
  id: string;
  location?: string;
  term?: string;
};
export const InventoryLocationDetailURI = createURI<InventoryLocationDetailInputType>("/inventory/locations/:id", {"id":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryLocationEditInputType = {
  id: string;
  location?: string;
  term?: string;
};
export const InventoryLocationEditURI = createURI<InventoryLocationEditInputType>("/inventory/locations/:id/edit", {"id":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryStockInputType = {
  itemId: string;
  location?: string;
  term?: string;
};
export const InventoryStockURI = createURI<InventoryStockInputType>("/inventory/stock/:itemId", {"itemId":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"term":{"kind":"string","optional":true}});


export type InventoryStockLocationInputType = {
  itemId: string;
  location?: string;
  locationId: string;
  term?: string;
};
export const InventoryStockLocationURI = createURI<InventoryStockLocationInputType>("/inventory/stock/:itemId/:locationId", {"itemId":{"kind":"string","optional":false},"location":{"kind":"string","optional":true},"locationId":{"kind":"string","optional":false},"term":{"kind":"string","optional":true}});


export type UserIndexInputType = {
};
export const UserIndexURI = createURI<UserIndexInputType>("/users", {});


export type UserNewInputType = {
};
export const UserNewURI = createURI<UserNewInputType>("/users/new", {});


export type UserDetailInputType = {
  id: string;
};
export const UserDetailURI = createURI<UserDetailInputType>("/users/:id", {"id":{"kind":"string","optional":false}});


export type RouteContextType =
  RouteContextValue<HomeInputType, RouteName.Home>
  | RouteContextValue<ItemIndexInputType, RouteName.ItemIndex>
  | RouteContextValue<ItemNewInputType, RouteName.ItemNew>
  | RouteContextValue<ItemDetailInputType, RouteName.ItemDetail>
  | RouteContextValue<ItemEditInputType, RouteName.ItemEdit>
  | RouteContextValue<LocationIndexInputType, RouteName.LocationIndex>
  | RouteContextValue<LocationNewInputType, RouteName.LocationNew>
  | RouteContextValue<LocationDetailInputType, RouteName.LocationDetail>
  | RouteContextValue<LocationEditInputType, RouteName.LocationEdit>
  | RouteContextValue<InventoryIndexInputType, RouteName.InventoryIndex>
  | RouteContextValue<InventoryNewInputType, RouteName.InventoryNew>
  | RouteContextValue<InventoryDetailInputType, RouteName.InventoryDetail>
  | RouteContextValue<InventoryEditInputType, RouteName.InventoryEdit>
  | RouteContextValue<InventoryItemDetailInputType, RouteName.InventoryItemDetail>
  | RouteContextValue<InventoryItemEditInputType, RouteName.InventoryItemEdit>
  | RouteContextValue<InventoryLocationDetailInputType, RouteName.InventoryLocationDetail>
  | RouteContextValue<InventoryLocationEditInputType, RouteName.InventoryLocationEdit>
  | RouteContextValue<InventoryStockInputType, RouteName.InventoryStock>
  | RouteContextValue<InventoryStockLocationInputType, RouteName.InventoryStockLocation>
  | RouteContextValue<UserIndexInputType, RouteName.UserIndex>
  | RouteContextValue<UserNewInputType, RouteName.UserNew>
  | RouteContextValue<UserDetailInputType, RouteName.UserDetail>;

const ROUTE_CONTEXT = createRouteContextRegistry<RouteContextType>();
export const HomeRouteContext = ROUTE_CONTEXT.forRoute(RouteName.Home);
export const ItemIndexRouteContext = ROUTE_CONTEXT.forRoute(RouteName.ItemIndex);
export const ItemNewRouteContext = ROUTE_CONTEXT.forRoute(RouteName.ItemNew);
export const ItemDetailRouteContext = ROUTE_CONTEXT.forRoute(RouteName.ItemDetail);
export const ItemEditRouteContext = ROUTE_CONTEXT.forRoute(RouteName.ItemEdit);
export const LocationIndexRouteContext = ROUTE_CONTEXT.forRoute(RouteName.LocationIndex);
export const LocationNewRouteContext = ROUTE_CONTEXT.forRoute(RouteName.LocationNew);
export const LocationDetailRouteContext = ROUTE_CONTEXT.forRoute(RouteName.LocationDetail);
export const LocationEditRouteContext = ROUTE_CONTEXT.forRoute(RouteName.LocationEdit);
export const InventoryIndexRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryIndex);
export const InventoryNewRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryNew);
export const InventoryDetailRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryDetail);
export const InventoryEditRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryEdit);
export const InventoryItemDetailRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryItemDetail);
export const InventoryItemEditRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryItemEdit);
export const InventoryLocationDetailRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryLocationDetail);
export const InventoryLocationEditRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryLocationEdit);
export const InventoryStockRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryStock);
export const InventoryStockLocationRouteContext = ROUTE_CONTEXT.forRoute(RouteName.InventoryStockLocation);
export const UserIndexRouteContext = ROUTE_CONTEXT.forRoute(RouteName.UserIndex);
export const UserNewRouteContext = ROUTE_CONTEXT.forRoute(RouteName.UserNew);
export const UserDetailRouteContext = ROUTE_CONTEXT.forRoute(RouteName.UserDetail);

export type HomeRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.Home }>;
export function useHomeRouteContext(): HomeRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.Home:
      return context;
    default:
      throw new Error('useHomeRouteContext requires the Home entrypoint; current route is ' + currentRoute);
  }
}

export type InventoryRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.InventoryIndex | RouteName.InventoryNew | RouteName.InventoryDetail | RouteName.InventoryEdit | RouteName.InventoryItemDetail | RouteName.InventoryItemEdit | RouteName.InventoryLocationDetail | RouteName.InventoryLocationEdit | RouteName.InventoryStock | RouteName.InventoryStockLocation }>;
export function useInventoryRouteContext(): InventoryRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.InventoryIndex:
    case RouteName.InventoryNew:
    case RouteName.InventoryDetail:
    case RouteName.InventoryEdit:
    case RouteName.InventoryItemDetail:
    case RouteName.InventoryItemEdit:
    case RouteName.InventoryLocationDetail:
    case RouteName.InventoryLocationEdit:
    case RouteName.InventoryStock:
    case RouteName.InventoryStockLocation:
      return context;
    default:
      throw new Error('useInventoryRouteContext requires the Inventory entrypoint; current route is ' + currentRoute);
  }
}

export type ItemRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.ItemIndex | RouteName.ItemNew | RouteName.ItemDetail | RouteName.ItemEdit }>;
export function useItemRouteContext(): ItemRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.ItemIndex:
    case RouteName.ItemNew:
    case RouteName.ItemDetail:
    case RouteName.ItemEdit:
      return context;
    default:
      throw new Error('useItemRouteContext requires the Item entrypoint; current route is ' + currentRoute);
  }
}

export type LocationRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.LocationIndex | RouteName.LocationNew | RouteName.LocationDetail | RouteName.LocationEdit }>;
export function useLocationRouteContext(): LocationRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.LocationIndex:
    case RouteName.LocationNew:
    case RouteName.LocationDetail:
    case RouteName.LocationEdit:
      return context;
    default:
      throw new Error('useLocationRouteContext requires the Location entrypoint; current route is ' + currentRoute);
  }
}

export type UserRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.UserIndex | RouteName.UserNew | RouteName.UserDetail }>;
export function useUserRouteContext(): UserRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.UserIndex:
    case RouteName.UserNew:
    case RouteName.UserDetail:
      return context;
    default:
      throw new Error('useUserRouteContext requires the User entrypoint; current route is ' + currentRoute);
  }
}
