/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/ClogTheme.ts
 * Command: astryx theme build src/theme/ClogTheme.ts --out src/theme/__generated__/clog.css
 * CLI: @astryxdesign/cli@0.6.3
 * Core: @astryxdesign/core@0.6.3
 */

/// <reference path="./clog.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const clogTheme: DefinedTheme;
